name: cetak_struk
description: "A new Flutter project."
publish_to: 'none' # Private package

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_text_recognition: ^0.15.0
  path_provider: ^2.1.5
  share_plus: ^11.1.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  provider: ^6.1.2

# Plugin blue_thermal_printer di-override pakai repo yang sudah patch namespace
dependency_overrides:
  blue_thermal_printer:
    git:
      url: https://github.com/kakzaki/blue_thermal_printer.git
      ref: master  # optional, bisa spesifik commit jika mau stabil

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.1
  flutter_lints: ^6.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/splash_icon.png
  android: true
  ios: true
  web: false
  fullscreen: true
  android_gravity: center
  ios_content_mode: center

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
